# Generated by Django 3.2.5 on 2021-07-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='decription',
            new_name='description',
        ),
    ]
